// Redux common reducer
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

// Redux production reducer
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const MOVE_PRODUCT_OF_WAREHOUSE = 'MOVE_PRODUCT_OF_WAREHOUSE'

//Redux warehouses reducer
export const ADD_PRODUCT_IN_WAREHOUSE = 'ADD_PRODUCT_IN_WAREHOUSE'
export const ADD_WAREHOUSE = 'ADD_WAREHOUSE'
export const DELETE_PRODUCT_IN_WAREHOUSE = 'DELETE_PRODUCT_IN_WAREHOUSE'
export const MOVE_PRODUCT = 'MOVE_PRODUCT'
export const DELETE_WAREHOUSE = 'DELETE_WAREHOUSE'

//Modal types
export const MODALS_TYPES = {
  VIEW_WAREHOUSE: 'VIEW_WAREHOUSE',
  VIEW_PRODUCT: 'VIEW_PRODUCT'
}